# This file describes the network interfaces available on your system
# For more information, see netplan(5).
#paok
#tsekaris
network:
  version: 2
  renderer: networkd
  ethernets:
    enp2s0:
      dhcp4: no
      dhcp6: no
      addresses: [172.16.6.3/24]
      gateway4: 172.16.6.241
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
    enp3s0:
      dhcp4: yes
      dhcp6: no
